apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  name: service-name-loadbalancer
spec:
  type: NodePort
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value#for creating a deployment in kubernetes
 kubectl apply -f spa-deployment.yaml
