apiVersion: v1
kind: Service
metadata:
  labels:
    app: ttech-web-app
  name: ttech-web
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: iaa-web-app
